set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)

set(_PROFILE_RELWITHDEBINFO_FLAGS
    "-O2 -g -DNDEBUG -fno-omit-frame-pointer")
set(CMAKE_C_FLAGS_RELWITHDEBINFO
    "${_PROFILE_RELWITHDEBINFO_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO
    "${_PROFILE_RELWITHDEBINFO_FLAGS}" CACHE STRING "" FORCE)
