set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)

set(_PROFILE_ASAN_FLAGS
    "-O1 -g -DNDEBUG -fno-omit-frame-pointer -fsanitize=address")
set(CMAKE_C_FLAGS_RELWITHDEBINFO
    "${_PROFILE_ASAN_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO
    "${_PROFILE_ASAN_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS
    "-fsanitize=address" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS
    "-fsanitize=address" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS
    "-fsanitize=address" CACHE STRING "" FORCE)
