#!/bin/bash
# 从 setup.bash 导出 CLion Python Run/Debug 用的 .env（固定脚本，手动或 post-create 执行）
# CLion 不能选 .sh 作解释器，请用 /usr/bin/python3 + scripts/ros2-clion.env
set -eo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/scripts/ros2-clion.env"

source "/opt/ros/${ROS_DISTRO:-jazzy}/setup.bash"
if [[ -f "${ROOT}/ws/install/setup.bash" ]]; then
  source "${ROOT}/ws/install/setup.bash"
fi

vars=(LD_LIBRARY_PATH PYTHONPATH AMENT_PREFIX_PATH COLCON_PREFIX_PATH ROS_DISTRO ROS_VERSION ROS_PYTHON_VERSION RMW_IMPLEMENTATION PATH)

{
  echo "# Generated by scripts/update-ros2-clion-env.sh — CLion Python Run/Debug"
  echo "# Regenerate after colcon overlay changes: bash scripts/update-ros2-clion-env.sh"
  echo ""
  for v in "${vars[@]}"; do
    if [[ -n "${!v:-}" ]]; then
      printf '%s=%s\n' "$v" "${!v}"
    fi
  done
  if [[ -f "${ROOT}/.env" ]]; then
    echo ""
    echo "# --- merged from ${ROOT}/.env ---"
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line%%#*}"
      line="$(echo "$line" | xargs)"
      [[ -z "$line" || "$line" != *=* ]] && continue
      key="${line%%=*}"
      if [[ -z "${!key:-}" ]]; then
        echo "$line"
      fi
    done < "${ROOT}/.env"
  fi
} > "${OUT}"

echo "Wrote ${OUT}"
